### PR TITLE
VMware CSI Storage integration

### PR DESCRIPTION
**Pull request by chris7444**

### CODE REVIEW

**Comment by moyni77** [comment]
LG.

**Comment by chris7444** [comment]
@daveolker 1024 (1TB) is the size of the VM datastore when I used to create it manually. That is the only reason why I chose this value. For the CSI Storage datastore, I though 1TB would be a massive amount of persistent volume data so I configured 512G.  I can fix the typos but I don;t know how I should spell OmniStack.  Omnistack ?  (Actually I was wondering if this was not an internal name.)

**Comment by chris7444** [comment]
I see them spelled OmniStack and SimpliVity (https://techhub.hpe.com/eginfolib/OmniStack_for_vSphere/admin_getstarted-intro/admin_getstarted_intro-about-this-guide.html) I will make the chang were needed

**Comment by chris7444** [comment]
typos fixed

**Pull request merged**
