### PR TITLE
Efk comments

### PR DESCRIPTION
**Pull request by chris7444**
Address comments in PR83

### CODE REVIEW

**Comment by chris7444** [comment]
@moyni77 Not sure where do you see the word "invalid"in this PR ?

**Comment by moyni77** [comment]
defauots/main.yml file has this, which I think is confusing.

efk_channel: "invalid"               # efk_channel must be configured in group_vars/all/vars.yml

**Comment by chris7444** [comment]
in vars.yml.sample I can change the default to 4.2 yes.

**Comment by chris7444** [comment]
(but

> defauots/main.yml file has this, which I think is confusing.
> 
> efk_channel: "invalid" # efk_channel must be configured in group_vars/all/vars.yml

you are looking at an old file

**Comment by chris7444** [comment]
Will leave Dave a chance to comment

**Comment by daveolker** [comment]
My expectation of a "default" variable value is this value should work with the playbooks if it is not being overridden elsewhere.  When looking at the default file for this EFK role:

efk_channel: "required"              # Mandatory. Must be supplied by the caller

"required" is not a valid value for this variable.  The comment in the file says this is a mandatory variable but makes no mention of the fact that this bogus local value will get ignored assuming a correct value is defined in the group_vars/all/vars.yml file.  Also, if the user does not properly define an overriding value in the group_vars/all/vars.yml file, I would expect this role to fail when it cannot find the proper channel for the EFK operator.

My preference is to either:

- Remove this entry from the defaults file and document that the user MUST define this variable in group_vars/all/vars.yml and assign it a meaningful value of "preview" or "4.2"

or

- Leave this entry in the role defaults file but set it to a proper value, which in this round is "4.2".  In this scenario I would comment out the matching value in the group_vars/all/vars.yml file as this default value would be correct for this version of the playbooks and there would be no need to override it with a proper value in the global vars.yml file.

As for role-based default variable values as a whole, I get the idea of defining default variables in the role to make the role "portable" (this was a stated concern/best practice in the past), so if that is the desired approach then we should define all variables needed by a role in their local defaults directory and set them to values that will work with the playbooks we deliver.  Obviously the user can modify these default values to match their environment if they choose (or override them in any number of places), but to make the role truly portable it should have any variables it needs defined locally with working values.

We can certainly explain to the user in the documentation that based on the Ansible rules of variable precedence, they can override default values defined in any role by including a matching variable in the global group_vars/all/vars.yml file.  There are also a number of other methods for overriding these role-based default variables, but one of our historical practices has been to include variables in a single location - group_vars/all/vars.yml.

If we take this approach, does that mean we need to include every one of these role-based default variables in the group_vars/all/vars.yml file and comment them out?  Or do we simply document this approach and let the user decide if they wish to override the role-based default values in the global vars file?

Thoughts?

**Comment by chris7444** [comment]
@daveolker 

""required" is not a valid value for this variable. The comment in the file says this is a mandatory variable but makes no mention of the fact that this bogus local value will get ignored assuming a correct value is defined in the group_vars/all/vars.yml file"

1- I can remove the comment if you don't like the comment (and in the future I will probably avoid putting comments in the roles because it seems to create too much unecessary discussions)

2- The end user is (should) only (be) concerned by the fact that this variable MUST be explicitly configured in group_vars/all/vars.yml. full point. Enduser don't have, MUST NOT, SHOULD NOT WILL NOT make any modification to roles.  They have ZERO reason to look into roles. The only files that should be configured by endusers are vars.yml and vault.yml. So there is absolutely ZERO reason to explain variable precedence to end users. if you think there is a need for this you are probably missing something important in the overall design.  Only YOU as a contributor needs to underatand variable precedence

(there is one exception with rhel worker group and I explained why we could tolerate this exception, and we can remove this exception if this exception prevents you from seeing the big picture)

3- The fact that efk_channel is defined in the role is for re-use purpose. to make it clear in case someone wants to re-use the role (and this is one of our goal) that this variable MUST be configured by the caller *(any playbook using this role). Again, if you don;t like the comment I can remove the comments.  Take/understand the default/main.yml file as a section of a traditional program where you can find the arguments that the role is accepting. (thinkthis as  a C program defining its arguments) 

4- Now the fact that in an ideal world we should do the same for all roles is very true but we are not living in an ideal world. If you want to make an extension to your house, you need to build new walls, and do the painting etc.  5 years after the house was build, you will use different bricks/stones, different paintings, because they are better, cheaper, they are more easy to deploy etc. But absolutely no one will rebuild and re-paint every single wall of the house unless there is a good reason for doing so. There is none

Finally having the default value set to 4.2 is the worst possible option,. The role needs to be modified every time we support a new version of OCP which is exactly the opposite of what we want to achieve with roles. And it is completelu unecessary because this variable MUST be defined in group_vars/all/vars.yml. I have made it clear in the release notes and in vars.yml.sample

**Comment by daveolker** [comment]
Sorry, I wasn't aware of the requirement that customers cannot ever touch an Ansible role.  If that is the case, I’m curious why Ansible even bothered to design roles to have “defaults” and “vars” directories in the first place.  I also wasn’t aware that once a role has variables defined in the “defaults” (and presumably "vars") directory that those values can never be modified – even by someone leveraging a role for a completely different set of playbooks.

Also, what makes the efk_channel variable so special that means it alone should have a bogus value assigned in the local role defaults directory and have a mandatory requirement that it be overridden by another declaration in the group_vars/all/vars.yml file?  Why aren’t the other three EFK variables defined in the same role defaults file assigned meaningless values in the role and overridden by the global vars file?  If users are never allowed to touch a role and they are only allowed to modify the global vars.yml file then shouldn't all variables for all roles be defined there?

I agree that we should not be hard-coding a version number in the role directories, but I noticed you removed the “ocp_version” variable from the global vars file.  My intention with declaring that variable once in the global vars file was to control all the roles, playbooks, and other OCP collateral that have version dependencies such as RHEL workers, RHCOS template names, and now EFK channels.  My expectation is that a customer deploying a specific version of OCP would only want to define that version number in one place and the rest of the playbooks would act accordingly by referencing the {{ ocp_version }} variable.  I’d be happy to remove the hard-coded ocp_version variable from the RHEL worker role and have it default to an ocp_version variable in the global vars file.

Is there a reason we cannot have efk_channel default to {{ ocp_version }} and control that via the global vars file?  Yes, we would have to override that for OCP 4.1 to use a value of “preview” (thanks a lot Red Hat), but OCP 4.1 will soon be unsupported and hopefully going forward Red Hat will keep the EFK channel value the same as the OCP version number.  Though with Red Hat, who knows...

**Comment by chris7444** [comment]
"Sorry, I wasn't aware of the requirement that customers cannot ever touch an Ansible role"

You are kidding here?  There is no requirement to make things complicated for an enduser when they can be simple.Let the user edit a single file and a password/secret file is simple. Let the user modify roles and explain them the subtleties of variable precedence is complicated for both us and the endusers! And there is absolutely zero reason for doing so.

"I’m curious why Ansible even bothered to design roles to have “defaults” and “vars” directories in the first place. "
You should make a distinction between users of ansible playbooks and developpers of ansible playbooks and this will help. A role should be considered as CODE, everything in the role directory is code INCLUDING the variables defined in vars and defaults folders (similarily a C program defines variables but you don;t want the endusers to changes the C program).  
Sticking to the parallel between a role and a C function or a C program,  a C program defines its arguments.  (eg myprog -name=foo -size=10) In the case of a role, the best place to define these arguments is the defaults folder.  In a C program some arguments are optional, some are mandatory.


"Also, what makes the efk_channel variable so special that means it alone should have a bogus value assigned in the local role defaults directory and have a mandatory requirement that it be overridden by another declaration in the group_vars/all/vars.yml file?"

because there is no meaningfull default value for efk_channel from the perspective of the role. I have answered that already

" Why aren’t the other three EFK variables defined in the same role defaults file assigned meaningless values in the role and overridden by the global vars file? "
because specifying 200G for `efk_es_pv_size` is a reasonable default. it will work with OCP4.2, OCP4.3, OCP4.4 probably and will not fail if this variable is not specified in group_vars/all/vars.yml.  From the enduser perspective this variable is optional in group_vars/all/vars.yml.  if they want to ignore this parameter (ie not configure it in group_vars/all/vars.yml) , they can, it will work, and it will work with OCP4.3 as well. Whereas a default value of "4.2" in the role for efk_channel is VERY likely (99.9%) to fail if people deploy OCP4.3. And I don;t want to have to touch code (here the efk role) because the channel to use with OCP4.x will change. group_vars/all/vars.yml from an ednuser perspective is data, the roles are code

"Is there a reason we cannot have efk_channel default to {{ ocp_version }} and control that via the global vars file"
yes, what we need  is the name of the channel to use.  As far as we know today there is no guarantee that there is a correlation between the channel to use and the version of OCP so I don't see a reason to add variables of they are not needed. Also having a role use a variable used outside of the role makes the role non portable anymore

I can also add that I would prefer by far not to have ansible idiomatics in vars.yml.sample such as {{ install-dir}} etc. This is implying that the enduser has some knowledge of ansible and jinja2 substitution

**Comment by chris7444** [comment]
and I think I already explained the difference between the variables defined in defaults and those defined in vars already and why it matters.

**Comment by daveolker** [comment]
“You should make a distinction between users of ansible playbooks and developpers of ansible playbooks and this will help. A role should be considered as CODE, everything in the role directory is code INCLUDING the variables defined in vars and defaults folders (similarily a C program defines variables but you don;t want the endusers to changes the C program).”

I guess we’ll just have to agree to disagree.

I don’t consider everything inside of a role to be CODE.  Most of the directories inside a role, yes.  The “defaults” and “vars” directories contain variables.  Variables are, by definition, configurable.  In my opinion, that makes them DATA.  You may prefer to leave them fixed and have users modify identically named variables in other locations, but that doesn’t change the fact that these are variables and can therefore be modified.

I understand your preference to use the global vars.yml file as a single configuration file.  While I can see the benefits with that approach, I also see benefits in keeping the variables associated with a role confined in their respective role directories.  As we’ve both stated, this makes the roles “portable”.  As long as the documentation clearly states where the variables are located and how to modify them, I can argue it’s cleaner to keep the role variables with their roles.

While we’re on the subject of role “portability”, which we’ve both agreed is important, there are roles in the current playbooks today that are not “portable” by this definition, meaning they reference role-specific variables that are not defined in their defaults or vars directories.  So which are we striving for - portability or ease of use?


“I can also add that I would prefer by far not to have ansible idiomatics in vars.yml.sample such as {{ install-dir}} etc.  This is implying that the enduser has some knowledge of ansible and jinja2 substitution”

Looking at the current vars.yml.sample file:

local_home: "{{ lookup('env','HOME') }}"
install_dir: "{{ local_home }}/.ocp"
ocp_installer_path: '{{ local_home }}/kits/openshift-install'
ocp_oc_path: '{{ local_home }}/kits/oc'
ocp_kubectl_path: '{{ local_home }}/kits/kubectl'
pull_secret: '{{ vault.pull_secret }}'
vcenter_password: '{{ vault.vcenter_password }}'
simplivity_password: '{{ vault.simplivity_password }}'
master_ova_path: '{{ local_home }}/kits/rhcos.ova'
worker_ova_path: '{{ master_ova_path }}'
support_ova_path: '{{ local_home }}/kits/hpe-rhel760.ova'
worker_template: '{{ master_template }}'
...

We use jinja2 substitution extensively throughout the vars.yml file today, many of which added by you.  Are you saying you now want to remove any variable substitution in the var.yml file?

**Comment by chris7444** [comment]
"I guess we’ll just have to agree to disagree."

No it is not a matter of you agreeing or not, it is about making the right things. And what you propose is not the right thing for many reasons including

""I don’t consider everything inside of a role to be CODE"

1- I am sorry but you should. A first illustration of that is how people use roles from galaxy. When people use roles they pull from galaxy, they don;t modify these roles. Actually, the roles are installed in some location on their file system and they don;t even need to know where this location is to use the role.  When they use these roles, they invoke them providing values to the "arguments" the roles expect (which are defined in defaults/main.yml).   Galaxy would not be possible is the way to make things "clean" was to tell people to change variables insides the roles. 

2- a role can be invoked with a specific value for one of its arguments and with another value another time. This is the very definition of arguments. You don;t tell the people to modify the variable "size" in a role for the role to create a disk of the size you want or you will end up having one role per disk size you need to configure.  You could tell me it is possible to use a "global" variable to achieve this but then your role is not portable anymore (the correct world is "self-contained") because it depends on some external variable specific to the project. It makes the re-use of the role in another project difficult
Also using a global variable for this purpose is much liike saying my function add() takes two global variables global_op1 and global_op2 and adds them. If you tell me your add() is better than add(op1,op2) then you are questioning years of structured programming.

3- Another example of why your approach is not right. YOURSELF you told us we would have to modify  the openshift-ansible playbooks to modify some of the data one of the role was using and you said we would not want to do it because we don;t own these playbooks.  But we use this playbooks  without changing a single line of code in these playbooks just by providing the data to one of the roles without changing the role. 

"As we’ve both stated, this makes the roles “portable”. As long as the documentation clearly states where the variables are located and how to modify them, I can argue it’s cleaner to keep the role variables with their roles."
You are taking function arguments (roles defaults) and the values which are passed to a function when it is invoked for the same thing which they are not. The role defines the arguments it accepts using defaults/main.yml. Having a role "ADD" define the variables op1 and op2 in defaults/main.yml is similar to a c function defining the arguments it accepts eg: int add(int op1, int op2)

Now the playbook invoke  the role doing something like this
role: add
  vars:
     op1:  3
     op2:  8

The role may define op1 and op2 with default values 2 and 4 respectively. but you don;t change the role because you want to add 3 with 8, or 10 with 23


"While we’re on the subject of role “portability”, which we’ve both agreed is important, there are roles in the current playbooks today that are not “portable” by this definition, meaning they reference role-specific variables that are not defined in their defaults or vars directories. So which are we striving for - portability or ease of use?"
I already answered this one, you are asking if we should be rebuilding the whole house when we use new and better material when building an extension to this house. The answer is no. Somehow you are saying "we should build the house extension the old way because this is what we did in the past". In the past we knew less than we know today that is why today we have roles which are not self-contained. Should we modify all of them. Not if there is no business reason for doing so. Should we continue to write non self-contained roles because this is what we did in the past. The answer is also no. 

"As long as the documentation clearly states where the variables are located and how to modify them, I can argue it’s cleaner to keep the role variables with their roles."
The problem here is that you are ignoring our own experience. Not only is it technically the wrong choice to have people modify roles for the reasons explained above but ourselves we had to struggle with this approach when our tech-ed did not know which variable to document and which ones not to document and started to document the details of the cloud-init machinery.  If the solution is difficult to document this should raise a flag.  Confining the enduser configuration to a single file and a secret file keeps things simple for EVERYONE including ourselves.


regarding the vars.yml.sample
"We use jinja2 substitution extensively throughout the vars.yml file today, many of which added by you. Are you saying you now want to remove any variable substitution in the var.yml file?"
I added these jinja2 subsitutions to ease your work (team) and avoid name collisions in the cluster. Yes, I am suggesting we should remove these jinja2 things from the sample as it is turning into code. But I was only throwing the idea here. And if you thought I am never questioning my own choices, you are proven wrong.

**Comment by chris7444** [comment]
"Why not set this to {{ efk_channel }} so it inherits the value of the variable set in the global vars file? This is the same approach used in other roles like LDAP."

I would not do it today because this makes the role dependant on external variables (and hence no longer self-contained)

This is what we call making progress. Overtime we learn (hopefully) and we don't do things the way we did in the past because we try to make them better, more efficient. etc (because we learn)  If the only reason you can invoke is to stick to what was done in the past with the assumption that they were perfect we would all be hunter gatherers today

**Comment by chris7444** [comment]
I insist on you approving because I believe this is critical you stop documenting your own PRs telling people to change variables inside roles and continue to do so.  I really believe I have provided you with plenty of explanations to support this request of mine.

**Pull request merged**
