### PR TITLE
Changes to enable RHEL worker scaling in OCP 4.2

### PR DESCRIPTION
**Pull request by daveolker**
This change, along with cloning an OCP 4.2 version of the OpenShift Ansible repository, allows RHEL workers to scale in OCP 4.2.  The updated OpenShift Ansible repository instructions will be updated separately in the documentation repository.

### CODE REVIEW

**Comment by daveolker** [comment]
Modified code to use ocp_version variable in places where the string "4.1" was used.

**Comment by chris7444** [comment]
you should supply a doc somehow for people to leverage your story. we discussed this yesterday during the team meeting and we don't want Gabriel to be the bottleneck. so dev provide doc for their story (raw material). I have created a release_notes.md for this purpose (same idea as the initial README.md)

**Comment by daveolker** [comment]
I agree we should document any new functionality added in the 4.2 version of the solution, or anything that requires any user-visible steps/knowledge to implement the same feature in 4.2.

In this case we're not adding anything new.  The playbooks will work exactly as they did with 4.1 to add RHEL worker nodes.  The only user-visible change will be the version of the OpenShift Ansible repository the user needs to clone to get the 4.2 version of the scaleup.yml playbook.  That involves a 3-line change to the 4.1 documentation and I've already sent that change to Gabriel.

**Comment by chris7444** [comment]
we need ro qa this work and to qa it we need to pull tje correct tag/release of the openshift-ansible repo so this information should be a part of the story.

**Comment by daveolker** [comment]
This PR is closed so I'll add that detail to the release notes document contained in your RHCOS scale PR.

**Pull request merged**
